/** @type {import('./src/tools/icons-config').IconsConfig} */
const config = {
  inputPath:
    "node_modules/@fontsource-variable/material-symbols-rounded/files/material-symbols-rounded-latin-full-normal.woff2",
  outputPath: "src/lib/assets/icons.min.woff2",
  icons: [
    "adjust",
    "add",
    "piano",
    "keyboard",
    "settings",
    "edit",
    "music_note",
    "avg_pace",
    "lyrics",
    "speed",
    "cognition",
    "update",
    "offline_pin",
    "warning",
    "dangerous",
    "check",
    "cable",
    "person",
    "sync",
    "school",
    "restart_alt",
    "usb",
    "usb_off",
    "rule_settings",
    "123",
    "abc",
    "function",
    "cloud_done",
    "backup",
    "cloud_download",
    "cloud_off",
    "share",
    "ios_share",
    "close",
    "arrow_back",
    "arrow_back_ios_new",
    "save",
    "settings_backup_restore",
    "sort",
    "shopping_bag",
    "filter_list",
    "settings_power",
    "link",
    "link_off",
    "chevron_right",
    "check_circle",
    "error",
    "auto_delete",
    "format_paint",
    "dark_mode",
    "light_mode",
    "palette",
    "translate",
    "play_arrow",
    "extension",
    "upload_file",
    "commit",
    "bug_report",
    "delete",
    "remove_selection",
    "bolt",
    "undo",
    "redo",
    "replay",
    "reply",
    "navigate_before",
    "navigate_next",
    "print",
    "restore_from_trash",
    "history",
    "history_toggle_off",
    "sentiment_satisfied",
    "sentiment_dissatisfied",
    "sentiment_very_satisfied",
    "sentiment_neutral",
    "sentiment_very_dissatisfied",
    "sentiment_excited",
    "sentiment_frustrated",
    "sentiment_calm",
    "sentiment_stressed",
    "sentiment_extremely_dissatisfied",
    "sentiment_sad",
    "sentiment_content",
    "sentiment_worried",
    "timer",
    "target",
    "download",
    "download_2",
    "upload_2",
    "stat_minus_2",
    "stat_2",
    "send",
    "more_horiz",
    "add_reaction",
    "stop",
    "description",
    "add_circle",
    "refresh",
    "tune",
    "edit_document",
    "chat",
    "account_circle",
    "experiment",
    "code",
    "dictionary",
  ],
  codePoints: {
    speed: "e9e4",
    arrow_split: "e985",
    arrow_circle_down: "f181",
    arrow_circle_up: "f182",
    counter_1: "f784",
    counter_2: "f783",
    counter_3: "f782",
    ios_share: "e6b8",
    light_mode: "e518",
    upload_file: "e9fc",
    no_sound: "e710",
    sentiment_extremely_dissatisfied: "f194",
    download_2: "f523",
    upload_2: "ff52",
    stat_minus_2: "e69c",
    stat_2: "e699",
    routine: "e20c",
    experiment: "e686",
    dictionary: "f539",
  },
};

export default config;
